export const ROUTE_NAME = {
    HOME: 'Homepage',
    HORMONE_REPLACEMENT_THERAPY_SERVICE: 'Hormone Replacement Therapy',
    LOW_DOSE_NALTREXONE_SERVICE: 'Low-Dose Naltrexone (LDN)',
    SEXUAL_HEALTH_SERVICE: 'Sexual Health for Men & Women',
    WEIGHT_LOSS_SERVICE: 'Weight Loss',
    HAIR_GROWTH_SERVICE: 'Hair Growth',
    DERMATOLOGY_SERVICE: 'Dermatology',
    PEDIATRICS_SERVICE: 'Pediatrics',
    VETERINARY_SERVICE: 'Veterinary',
    OUR_TEAM: 'Our Team',
    OUR_FACILITY: 'Our Facility',
    PROFESSIONAL_PARTNERSHIP: 'Professional Partnership',
    FAQ: 'FAQ',
    CONTACT_US: 'Contact Us - About Us',
    WHAT_IS_COMPOUNDING: 'What Is Compounding',
    WHY_CHOOSE_US: 'Why Choose Us',
    HORMONE_THERAPY_CONSULTATION: 'Book a Hormone Consultation',
    CONTACT_US_PAGE: 'Contact Us',
    GETTING_STATED: 'Getting Started',
    NEW_PATIENT_INTAKE: 'New Patient Intake Form',
    FILL_MY_RX: 'Fill My Rx'
}

export const PATH = {
    HOME: '/',
    HORMONE_REPLACEMENT_THERAPY_SERVICE: '/services/hormone-replacement-therapy',
    LOW_DOSE_NALTREXONE_SERVICE: '/services/low-dose-naltrexone',
    SEXUAL_HEALTH_SERVICE: '/services/sexual-health-for-men-and-women',
    WEIGHT_LOSS_SERVICE: '/services/weight-loss',
    HAIR_GROWTH_SERVICE: '/services/hair-growth',
    DERMATOLOGY_SERVICE: '/services/dermatology',
    PEDIATRICS_SERVICE: '/services/pediatrics',
    VETERINARY_SERVICE: '/services/veterinary',
    OUR_TEAM: '/our-team',
    OUR_FACILITY: '/our-facility',
    PROFESSIONAL_PARTNERSHIP: '/professional-partnership',
    FAQ: '/faq',
    CONTACT_US: '/about-us/contact-us',
    WHAT_IS_COMPOUNDING: '/patients/what-is-compounding',
    WHY_CHOOSE_US: '/patients/why-choose-us',
    HORMONE_THERAPY_CONSULTATION: '/consultation/hormone-therapy',
    CONTACT_US_PAGE: '/contact-us',
    GETTING_STATED: '/patients/getting-started',
    NEW_PATIENT_INTAKE: '/patients/new-patient-intake',
    FILL_MY_RX: '/patients/fill-my-rx'
}